title: YoLo
author: Remi 
email: thisisme@domain.com
description: > # this means to ignore newlines until "baseurl:"
  BANANA,
  This sh*t is BANANA,
  B, A, N, A, N, A!

# social links
twitter_username: doremito
github_username:  remiconnesson

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
